version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:14
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432

volumes:
  postgres_volume:
  redis_volume:
